### ISSUE TITLE
Galley for the article html 

### ISSUE THREAD

**Issue by tnier01** [o2r-project/ojs-erc-plugin#12]
In addition to the o2r UI in a galley there should be a further galley which is just showing the html of ther article. 
There are different options: 
- [ ] 1. ~~the whole ERC can be downloaded, unzipped and the article html uploaded as galley (not that useful if we only want to show the html, if we also want to show other files this could be useful)~~ 
- [ ] 2. create an iframe/ html which calls there the html of the ERC and create this as galley 
- [ ] 3. download the ERC html and store/ create it as galley (perhaps the best option, then we could use this html not only for a galley but perhaps also as main submission 

- [ ] perhaps there is also the option to extract the abstract and also all the other data known from o2r of the ERC and use it as submission information in OJS – propably an idea for later 

In this context it could be senseful that the user has the choice during submission concerning what happens with the inserted ERC Id. There could be the following options which can be selected by the user through checkboxes:  
- [ ] The ERC Id is stored in the database 
- [ ] The ERC is shown in a galley in the format of the o2r UI 
- [ ] The article of the ERC is shown as html in a galley

**Comment by NJaku01** [comment]
There are two steps necessary to get the HTML of the article:

1. Get the name of the display file:
       -  Query the metadata: api/v1/compendium/_ercID_/metadata
       - Get the name of the display file under: response.data.metadata.o2r.displayfile

```
axios.get("localhost/api/v1/compendium/<ercID>/metadata)
   .then(function (response) {
             displayfileName= response.data.metadata.o2r.displayfile
             });
```
 


2.  Get the file itself
      - Download the file under: api/v1/compendium/_ercID_/data/_displayfileName_  (Option3) OR
      - Embet the file inside an iframe (0ption2)


 ```
<html>
<body>

<iframe src="http://localhost/api/v1/compendium/<ercID>/data/<displayfileName>" 
</iframe>

</body>
</html>
 ```

**Comment by nuest** [comment]
Re. the galley, the third options sounds good but I'm not sure and trust your assessment.

Re. the choice during submission: that should not be something that the user decides, but what a journal manager might configure. IMO all three should happen, but the journal manager may choose which options are shown to the reader (ERC acticle galley, ERC interactive galley, both?). The ERC ID should always be stored in the DB, right? Don't forget: submission by ID is effectively an intermediate solution until we can create an ERC during submission.
