### ISSUE TITLE
Reader can view ERC in the ERC Viewer started by the OJS Article View 

### ISSUE THREAD

**Issue by tnier01** [o2r-project/ojs-erc-plugin#2]
This issue is kind of the starting point. There are further issues which describe the tasks in more detail.  

User Story: As a reader, I can view the research compendia in the article view. 

There are two possibilities for this: 
- either directly in the article view: 
<img width="300" src="https://user-images.githubusercontent.com/46532733/100442794-ec2dde00-30a8-11eb-94ff-b5e78a2c52ab.png">

- or by a new tab (The user clicks the "RC" button and in a new tab the research compendium is viewable. In a new tab the o2r-UI gets opened):
<img width="300" src="https://user-images.githubusercontent.com/46532733/100442807-f18b2880-30a8-11eb-8f24-fbc661c34bc9.png">
<img width="300" src="https://user-images.githubusercontent.com/46532733/100442818-f64fdc80-30a8-11eb-980e-6770604611fa.png">

- API URL: https://o2r.uni-muenster.de/api/v1/compendium/q7Eje, Homepage URL https://o2r.uni-muenster.de/#/erc/q7Eje

- [x] store the ID of an ERC in a new field of the database 
- [x] store the server URL via the plugin settings 
- [x] open a HTML in a new tab by button push on the article view 
- [x] in the HTML a hidden field should call up the API URL and the responded JSON should be displayed correspondingly in a HTML div (jquery API Call)
- [x] the user can insert in the plugin's settings the o2r server URL 
- [x] if the build is loaded for the first time, the usual server url `https://o2r.uni-muenster.de/api/v1/`proposed and used. Later on the user can change it in the plugin settings 
- [x] the user should see in the plugin settings wich URL is currently used. 
- [x] a backlink is needed to get back to the article view 
- [x] The design of the new tab should be adapted accordingly to OJS
- [x] in the div not longer only the JSON response should be displayed but a build of the o2r UI
- [x] in the URL of the galley it should be "erc-342" and not "ErcId-342"
- [x] is it possible to integrate the html without iframe? -> Currently there are no straight forward possibilities to create a galley without iframe, but there are considerations in this direction (https://forum.pkp.sfu.ca/t/html-galleys-and-iframes-in-ojs-3-2/62596/7)
- [x] the final galley html element should only be stored in a temporary folder (is there a php function to do this?) before it gets stored at its final place

The basis html for the galley gets specified by the plugin concerning the following points: 
- [x] the build should also be specified in the sense that it is an OJS usage, so the variable OJS of the build must be set to true. 
- [x] the server url must be set to the o2r url, which is given by the user in the plugin settings 
- [x] the theme must be set, which is given by the user in the plugin settings 
- [x] the ercId must be set, which is given by the user during the submission process  

The Idea is that the user inserts during the submission process an ErcId. Based on this ErcId an galley is created which is a "stripped down" version of the o2rUI. This galley gives the possibility for viewing, manipulating and inspecting (The o2r-UI runs then of course locally on the device, but the ERC content data is requested from the o2r API). Therefore a production build of the o2r UI needs to be integrated inside the plugin. How this can work exactly, if a build of the o2r UI ("npm run build") is already created when activating the plugin from the OJS Plugin Gallery, or the code of the o2r UI is downloaded zipped by the plugin, the js files are integrated correspondingly in the plugin and then a corresponding production build is created, still has to be determined/tried out.

**Comment by tnier01** [comment]
After download of the current build the config.js needs to be adapted: 
- baseURL as the user specified it in the plugin settings     
- ojsView must be set to true 
- the follwing links directory must be updated to the plugin directory where the static folder is 
`<link rel="shortcut icon" href="/logo.png" />`
`<link rel="manifest" href="/manifest.json" />`
`<link href="/static/css/2.48fcd7aa.chunk.css" rel="stylesheet">`
`<link href="/static/css/main.5b4a0fad.chunk.css" rel="stylesheet">`
`<script src="/static/js/2.d42281d8.chunk.js"></script>`
`<script src="/static/js/main.36410696.chunk.js"></script>`

If a galley is created:
- the ErcId must be inserted by a simple js chunk in the html file between the config.js and the following static loading scripts

**Comment by tnier01** [comment]
- There are corse conflicts for the following links: 
`https://o2r.uni-muenster.de/api/v1/auth/whoami` 
`https://o2r.uni-muenster.de/api/v1/link`
`https://o2r.uni-muenster.de/api/v1/inspection/geQfc?file=data/NDVIchanges.Rdata`
`http://o2r.uni-muenster.de/api/v1/compendium/1myjp` in contrast `https://o2r.uni-muenster.de/api/v1/compendium/1myjp` works
- in contrast to `http` the baseUrl works with `https`, should we generally switch to `https`

**Comment by nuest** [comment]
- Yes, always use `https` _when available_
- I guess `localhost/api/v1` is correct for testing, but the plugin's default should be `o2r.uni-muenster.de`
- "corse conflicts" - do you mean CORS issus?
  - the `api/v1/inspection` should not work anymore, because the microservice is not developed further. Don't rely on that.
  - I have no idea why `/auth/whoami` does not have the CORS headers, the configuration is exactly the same.

@NJaku01 Can you take a look at these comments, please?

**Comment by tnier01** [comment]
- Yes of course CORS issues were meant. There were also problems for: 
`https://o2r.uni-muenster.de/api/v1/job/`
-  current state regarding iframe in galley: I think currently there are no straight forward possibilities to create a galley without iframe, but there are considerations in this direction (https://forum.pkp.sfu.ca/t/html-galleys-and-iframes-in-ojs-3-2/62596/7)

**Comment by tnier01** [comment]
The general implementation of making ERC viewable in the OJS Article View as it is described in this issue is done. There are some minor tasks that still need to be done, but basically viewing and manipulating ERCs in OJS works. With it this issue can be closed.
